server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: service-a-route
          uri: lb://service-a
          predicates:
            - Path=/service-a/**
        - id: service-b-route
          uri: lb://service-b
          predicates:
            - Path=/service-b/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
